### Переменная - базовый URL 
@baseUrl = http://localhost:5143

### GET 
### Получить все задачи
GET {{baseUrl}}/api/tasks

### Получить только выполненные задачи
GET {{baseUrl}}/api/tasks?completed=true

### Получить только невыполненные задачи
GET {{baseUrl}}/api/tasks?completed=false

### Получить задачу по id
GET  {{baseUrl}}/api/tasks/1

### Получить несуществующую задачу
GET {{baseUrl}}/api/tasks/999

### POST
### Создать новую задачу
POST {{baseUrl}}/api/tasks
Content-Type: application/json

{
    "title": "Задача из REST Client",
    "description": "Создана через файл .http",
    "priority": "High"
}
### Попытка создать задачу без заголовка (ожидаем 400)
POST {{baseUrl}}/api/tasks
Content-Type: application/json

{
    "title": "",
    "description": "Без заголовка",
    "priority": "Normal"
}
### PATCH 
### Переключить статус задачи с id=2
PATCH {{baseUrl}}/api/tasks/2/complete
### PUT
### Обновить задачу с id=1
PUT {{baseUrl}}/api/tasks/1
Content-Type: application/json

{
    "title": "Изучить ASP.NET Core (обновлено)",
    "description": "Контроллеры, маршруты, DTO",
    "isCompleted": true,
    "priority": "High"
}
### DELETE
### Удалить задачу 
DELETE {{baseUrl}}/api/tasks/4

### Поиск задач
GET {{baseUrl}}/api/tasks/search?query=ASP

### Задачи с высоким приоритетом
GET {{baseUrl}}/api/tasks/priority/High

### Статистика 
GET {{baseUrl}}/api/tasks/stats

### Отсортиованные задачи по приоритету
GET {{baseUrl}}/api/tasks/sorted?by=priority&desc=false